<?php
include("includes/header.php");
include("includes/nav.php");
include("includes/carousel.php");
include("includes/login_inc.php");
include("includes/logout.php")
include("includes/conn_1dt.php");
include("includes/footer.php");
include("includes/available_movies.php");
include("includes/about_movie_the_odyssey.php");
include("includes/about_movie_jurassic_world_rebirth.php");
include("includes/about_movie_batman_begins.php");
include("includes/about_movie_nosferatu.php");
include("includes/about_movie_spider_man_brand_new_day.php");
include("includes/about_movie_star_wars_return_of_the_jedi.php");
include("includes/manage_loans.php");
include("includes/view_loans.php");
include("includes/save_loans.php");
include("includes/return_loans.php");
?>