<?php
include("includes/header.php");
include("includes/nav.php");
include("includes/carousel.php");
include("includes/login_inc.php");
include("includes/footer.php");
include("includes/available_movies.php");
include("includes/about_movies.php");
?>